# Generated by Django 5.0.7 on 2024-07-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'штука',
                'verbose_name_plural': 'штуки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/photo', verbose_name='фото товара')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='дата создания записи в БД')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='дата последнего изменения записи в БД')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['price', 'name'],
            },
        ),
    ]
